### ISSUE TITLE
Add ability to not add the confirmation step

### ISSUE THREAD

**Issue by WonderCsabo** [ernestoyaquello/VerticalStepperForm#22]

**Comment by ernestoyaquello** [comment]
Whilst this feature is a really good idea (I have thought about it several times), it is really difficult to implement because of the way the library is coded. Maybe some day I will add it, but right now I do not have time to do it. Thanks for the suggestion anyway, I will keep it in mind!

**Comment by abeemukthees** [comment]
I'm also looking for this feature, I tried modifying it & somehow removed the last confirmation step, but the stepper line is visible always if I set showVerticalLineWhenStepsAreCollapsed(true) which looks bad. Hope to see this feature soon.

**Comment by syntaxerror1972** [comment]
@WonderCsabo i checked ur lib but there no any code to hide  confirmation step.

**Comment by syntaxerror1972** [comment]
hey @WonderCsabo  i got it thanks a lot........................
good work kip it up

**Comment by rebdev** [comment]
Seconding this would be a nice option. Was there any plan to integrate abeemukthees' implementation?

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding this issue, I am going to close it because the new version of the library, which has been completely refactored, already includes the ability to not add the confirmation step. Please go check it our in case you are still interested!

**Comment by WonderCsabo** [comment]
Hey, thanks for the response anyway! Keep up the good work. :)
