### ISSUE TITLE
Add List-based API for providing steps

### ISSUE THREAD

**Issue by WonderCsabo** [ernestoyaquello/VerticalStepperForm#24]
Nowadays most APIs use more convenient Lists instead of arrays, so it would be great if this library would allow to feed lists directly for steps.

**Comment by ernestoyaquello** [comment]
You are certainly right. I will include this feature in the next version. Thanks!

**Comment by ernestoyaquello** [comment]
The new builder now accepts that you set up the list by passing as many steps as you please as parameters, so I will close this issue because it is not really relevant anymore.

By the way, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.
