### ISSUE TITLE
Remove Continue Button

### ISSUE THREAD

**Issue by vlonjatg** [ernestoyaquello/VerticalStepperForm#35]
There are scenarios where we need to handle the navigation of the Stepper ourself like for example when a step has two buttons, instead of having to click on one of the buttons and then click continue, we can navigate to the next step on the initial button click.

So would it be possible to hide/remove the continue button for certain steps?

**Comment by draxdave** [comment]
+1

**Comment by vzool** [comment]
Yes, same here

**Comment by ahmadii** [comment]
+1

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding the issue, this is no longer a problem in the new version of the library because now you can opt to remove the step buttons in order to add your own in the step layout. Please go check out the new version if you are still interested.
