### ISSUE TITLE
Please help. I've done everything correctly, but the stepper doesn't show up.

### ISSUE THREAD

**Issue by GabrielKuka** [ernestoyaquello/VerticalStepperForm#42]
Couldn't resolve resource @id/down_next. (5 similar errors not shown)

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding the issue, I have no idea why it was happening and I don't have enough information here to try to guess it. In any case, I have refactored the whole library, so I am going to assume that this issue is no longer happening now. If you still happen to be interested, please go check out the new version of the library.
