### ISSUE TITLE
Keyboard Input Type Change Problem

### ISSUE THREAD

**Issue by WiliamGP** [ernestoyaquello/VerticalStepperForm#68]
Hi, 

Every time an edittext with a different input type is focused, the page scroll to the top.

For example, I have one editbox for the name and another for the age. When I type the age and the keyboard is changed, the page scroll to the top.

How can I solve this?

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding the issue, the "problem" is that, in order to allow the user to keep the currently open step in sight, the form will automatically scroll to the open step whenever the screen configuration changes.

I have recently refactored the library and improved the behaviour of the form in regards to automatic scrolling, so please check out the new version of the library in case you are still interested.
