### ISSUE TITLE
Linear Stepper Non-Editable after completed

### ISSUE THREAD

**Issue by Dewsworld** [ernestoyaquello/VerticalStepperForm#83]
Hello,

First of all, thank you for such a wonderful and useful library. I am struggling with an issue. In my case, the step should be editable for once only. Can I do that?

Thank you!

**Comment by ernestoyaquello** [comment]
There is no concept of "editable/non-editable step" in this library, so I am not sure I know what you are referring to. If your issue is related to getting an `EditText` view to be disabled at some point during the user workflow, then it is up to you to make that happen. Could you please provide more detail into what you are trying to achieve? Thanks!

**Comment by ernestoyaquello** [comment]
It has been more than a month and still no response, so I am going to close the issue.

**Comment by MrNouri** [comment]
Thank for this great library dear @ernestoyaquello .
Can you add this feature ? I need this feature too

**Comment by ernestoyaquello** [comment]
As I said, there is no concept of editable/non-editable steps in this library. If what you want is to be able to keep on using the form once a completion attempt or a cancellation attempt has been performed, then you can re-enable the entire form by calling `verticalStepperForm.cancelFormCompletionOrCancellationAttempt()` (more info about it in the documentation). I hope that helps!
