### ISSUE TITLE
Change lastStepNextButton color

### ISSUE THREAD

**Issue by MrNouri** [ernestoyaquello/VerticalStepperForm#91]
I want change color of lastStepNextButton in this library but not found any attribute !
I found this lastStepCancelButtonColors but this is for cancel button, i want change lastStepNextButton color !

how can i it?

**Comment by ernestoyaquello** [comment]
Hi, you should use the method `nextButtonColors()` of the builder in order to change the colour of the main buttons. Alternatively, you can use the XML attributes `form_next_button_background_color`, `form_next_button_pressed_background_color`, `form_next_button_text_color` and `form_next_button_pressed_text_color`.

I hope this helps!
