### ISSUE TITLE
How to save custom object in method onSaveInstanceState

### ISSUE THREAD

**Issue by abarazal** [ernestoyaquello/VerticalStepperForm#92]
I need to restore my data by implementing onRestoreInstanceState method, however how can I save a custom object in method onSaveInstanceState? I coud not found any example about this in your repo.

**Comment by ernestoyaquello** [comment]
This library doesn't do anything special to save and restore data, as it relies on the native Android implementation. Thus, you will need to serialise your data in order to be able to save it and restore it. There are multiple ways to achieve this, so I suggest you look it up. I personally prefer using the library [Gson](https://github.com/google/gson).
