### ISSUE TITLE
How can i call startActivityForResult?

### ISSUE THREAD

**Issue by biko2002you** [ernestoyaquello/VerticalStepperForm#93]
hello, i am using your library and in one of my steps i want open the users gallery and pick a photo , or from camera , 
i cant achieve this in the step as it cant override the onActivityResult void ..

how can i fix this , 
the parent is a fragment btw.

**Comment by ernestoyaquello** [comment]
Certainly, you cannot override `onActivityResult` inside a step, but you don't need to. Override it in your fragment or your activity and then proceed to ask for the picture from within the step. Please take a look at #89 to see if the approach discussed there could suit your needs.

**Comment by biko2002you** [comment]
Hello , Thank you for your reply and your gorgeous Library , 
i have checked the issue#89 and its quite helpful , but i have and extra thing i need to do it , as i am using the same scenario (selecting picture from gallery and uploading it) .
i need to notify the step that photo has been chosen from gallery and set to the ImageView preview ,  in order to call the markAsCompleteorUncomplete(true) .

so how can i call it after all work is done to end the step and proceed to the next one .

**Comment by TobiPristupin** [comment]
Leaving this here so it can help others. I had this same problem. Once I got my results from `onActivityResult` on the enclosing activity, I wanted to communicate that data to the step. I made a method in my step like follows:

```
public void updateData(Data data){
    //do whatever with data
}
```

The enclosing activity had a global reference to each step, so I just had to call `myStep.updateData` in `onActivityResult`. However, this caused a bug where when I called `updateData`, all the Views of my Step class were null. `getContentLayout()` and `getContext` were both returning null for some reason. I solved this by getting a reference to the corresponding step class through the stepper, instead of through the global reference. For example:

```
//In enclosing activity

private VerticalStepperFormView stepper;
private MyStepClass myStep;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ...

        stepper = findViewById(...)
        myStep = new MyStepClass();
        //initialize stepper with myStep
    }

   @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable @org.jetbrains.annotations.Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        Data intentData = getData(); //extract data from intent
       
        //DO NOT DO THIS.  
        myStep.updateData(data);
    
       //DO THIS
       MyStepClass step = (MyStepClass) stepper.getOpenStep();
       step.updateData(data);
}

```
